from mongoengine import IntField, FloatField, DateTimeField, Document, StringField, ListField

class CVEVulnerability(Document):
    cve_ID = StringField(required=True, unique=True)
    description = StringField(required=True)
    affected_vendors = StringField()
    affected_products = StringField()
    attack_vector = StringField()
    catalogVersion = StringField()
    cisa_exploitability_metric = StringField()
    count = IntField()
    cpe_configurations = ListField(StringField())
    cvss_access_vector = StringField()
    cvss_access_complexity = StringField()
    cvss_authentication = StringField()
    cvss_availability_impact = StringField()
    cvss_base_score = FloatField()
    cvss_confidentiality_impact = StringField()
    cvss_exploitability = FloatField()
    cvss_impact_score = FloatField()
    cvss_integrity_impact = StringField()
    cvss_vector = StringField()
    cwes = ListField(StringField())
    dateAdded: DateTimeField()
    dateReleased = StringField()
    dueDate = DateTimeField()
    impact_score = StringField()
    known_exploit = StringField()
    knownRansomwareCampaignUse = StringField()
    last_modified_date = DateTimeField()
    nested_data = StringField()
    notes = StringField()
    product = StringField()
    published_date = DateTimeField()
    references = StringField()
    requiredAction = StringField()
    severity = StringField()
    shortDescription = StringField()
    title = StringField()
    vendorProject = StringField()
    vulnerabiliityName = StringField()

    class Meta:
        db_table = 'c_v_e_vulnerability'  # Specify the collection name