from mongoengine import IntField, DictField, FloatField, DateTimeField, Document, StringField, ListField

class MEVulnerability(Document):
    cve_id = StringField(required=True, unique=True)
    description = StringField(required=True)
    cpe_configurations = ListField(StringField())
    cwes = ListField(StringField())
    cisa_exploitability_metric = StringField()
    cvss_base_score = FloatField()
    cvss_vector = StringField()
    cvss_access_vector = StringField()
    cvss_access_complexity = StringField()
    cvss_authentication = StringField()
    cvss_confidentiality_impact = StringField()
    cvss_integrity_impact = StringField()
    cvss_availability_impact = StringField()
    cvss_exploitability_score = FloatField()
    cvss_impact_score = FloatField()
    published_date = DateTimeField()
    last_modified_date = DateTimeField()

class CVEVulnerability(Document):
    cve_id = StringField(required=True, unique=True)
    description = StringField(required=True)
    published_date = DateTimeField()
    severity = StringField()
    attack_vector = StringField()
    impact_score = StringField()
    references = StringField()
    cvss_vector = StringField()
    affected_vendors = StringField()
    affected_products = StringField()
    nested_data = StringField()
    catalogVersion = StringField()
    title = StringField()
    count = IntField()
    vulnerabilities = ListField(DictField())
    dateReleased = StringField()
    cpe_configurations = ListField(DictField())
    cwes = ListField(StringField())
    cisa_exploitability_metric = StringField()
    cvss = DictField()
